spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: root@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 1000
      max-lifetime: 1800000
      connection-timeout: 30000

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/td/common/mapping/*.xml

spider:
  seleniumPath: /tmp/chromedriver
  count: 2
  tessdataDir: /data/tessdata
  imgDownadDir: /tmp/mimvpimg
  csvDownloadDir: /tmp/csv
  backTraceLogDir: /tmp/backTrace
  proxyType: 2

# 熊猫代理
xiongmao:
  secret: xxx
  orderNo: xxx

# 百度sdk应用
baidu:
  sdk:
    apkKey: xxx
    secretKey: xxx

# 钉钉webhook
dingding:
  webHook: https://oapi.dingtalk.com/robot/send?access_token=xxx

logging:
  config: classpath:log4j2.xml

#配置REST服务端口
server:
  port: 5000
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

