spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: root@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 1000
      max-lifetime: 1800000
      connection-timeout: 30000

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/td/common/mapping/*.xml

# 钉钉webhook
dingding:
  webHook: https://oapi.dingtalk.com/robot/send?access_token=xxx

logging:
  config: classpath:log4j2.xml

#配置REST服务端口
server:
  port: 5001

